[user]
player1_algorithm = "alpha_beta"
player2_algorithm = "human"
player1_depth = 3
player2_depth = 3

[graphics]
graphics_enabled = true
player1_symbol = "X"
player2_symbol = "O"

[game]
board_width = 5
board_height = 5
to_align = 4

[mcts]
exploration_constant = 2.0
simulations_per_iteration = 100

[model]
iterations = 20
self_play_iterations = 100
epochs = 4
batch_size = 64
temperature = 1
