[user]
player1_algorithm = "alpha_beta"
player2_algorithm = "human"
player1_depth = 3
player2_depth = 3

[graphics]
graphics_enabled = true
shell_graphics = false
player1_symbol = "X"
player2_symbol = "O"

[game]
row_number = 3
column_number = 3
to_align = 3

[mcts]
exploration_constant = 1.41
stable_iterations = -1 # -1 for no limit
simulations_per_iteration = 10000

[model]
training_enabled = false
training_iterations = 20
self_play_iterations = 100
epochs = 4
batch_size = 64
temperature = 1
