[user]
player1_algorithm = "mcts"
player2_algorithm = "human"
player1_depth = 3
player2_depth = 3

[graphics]
graphics_enabled = true
shell_graphics = false
player1_symbol = "X"
player2_symbol = "O"

[game]
row_number = 3
column_number = 3
to_align = 3

[mcts]
exploration_constant = 1.41
stable_iterations = -1 # -1 for no limit
simulations_per_iteration = 2000

[alpha_zero]
training_enabled = false
training_iterations = 40
using_ray = true
self_play_iterations = 200
learning_rate = 0.001
epochs = 8
batch_size = 128
temperature = 1
