[user]
player1_algorithm = "alpha_zero"
player2_algorithm = "human"
player1_depth = 4
player2_depth = 5

[graphics]
graphics_enabled = true
shell_graphics = false
player1_symbol = "X"
player2_symbol = "O"

[game]
row_number = 5
column_number = 5
to_align = 4

[mcts]
exploration_constant = 1.41
stable_iterations = -1 # -1 for no limit
simulations_per_iteration = 2000

[alpha_zero]
training_enabled = true
training_iterations = 40
using_ray = true
self_play_iterations = 200
learning_rate = 0.001
epochs = 8
batch_size = 128
temperature = 1
